### ISSUE TITLE
CP Page Load Speed Issues with Minify Enable

### ISSUE THREAD

**Issue by artsigns** [nystudio107/craft3-minify#10]
I recently started having issues with CP page load speeds. In trying to troubleshoot the issue I disabled all my plugins and enabled them one by one. I found that the speed issues start occurring when toggling the Minify plugin and that things returns to normal when the plugin is disabled.

What would be the best way to further troubleshoot this issue?

**Comment by khalwat** [comment]
@artsigns Sorry I didn't see this until now, let me know if this is still an issue for you.

But Minify doesn't do anything inside of the CP, that's very confusing to me...? It only does something when you have a template that has `{% minify %}` tags in it.

**Comment by artsigns** [comment]
I'm not sure why this was happening but I managed to fix it. It's been a while now so I can't quite remember how but I'll let you know if it happens again.
