### ISSUE TITLE
Incorrectly strips required code inside SVGs

### ISSUE THREAD

**Issue by MattWilcox** [nystudio107/craft3-minify#12]
This is a valid SVG:
http://hbleisure.website.viewcreative.agency/assets/images/world-map.svg

Including it on a page works fine: http://hbleisure.website.viewcreative.agency only if `{% minify %}` ... `{% endminify %}` does not wrap the SVG.

If there's minify applied around it, minify appears to strip `<![CDATA[` and `]]>` from inside the SVG, which causes the SVG to break.

**Comment by khalwat** [comment]
@MattWilcox This is an issue you'd need to file upstream, to the Minify library that Minify uses: 

https://github.com/mrclay/minify/issues

I did a quick search, and there is a semi-related open issue on `<![CDATA` already
