### ISSUE TITLE
It's just not working. 

### ISSUE THREAD

**Issue by ambidustrious** [nystudio107/craft3-minify#14]
I've added the Minify tags on my layout template...

```
{%- minify -%}
    (Entire base HTML/Twig template here)
{%- endminify -%}
```

My output doesn't reflect any compression at all. I have no caching on at the moment and any basic template changes are reflected immediately.

I've also attempted the minify smaller bits of code in my twig templates.. like this...

```
{% minify %}
    <a href="{{entry.url}}" class="col-12 col-lg-6 blog-item blog-item-big "> 
	    <div class="blogshadow">
		    <div class="bi-image bi-eq">
				{% set optimizedImages = entry.blogImage.one().optimizedBlogThumbnail %}
				<picture>
			        <source data-srcset="{{ optimizedImages.srcsetWebP() }}" 
			                data-sizes="100vw"
			                type="image/webp" />
			        <img class="lazyload"
			             src="{{ optimizedImages.placeholderBox() }}"
			             data-srcset="{{ optimizedImages.srcset() }}"
			             data-sizes="100vw" />
			     </picture>			    
			    <div class="bi-gradient"></div>
		    </div>
		    <div class="bi-content eq2">
			    <p class="bi-category">
				    {% for category in entry.category %}
				    {{ category.title }}{{ not loop.last ? ', ' }}
				    {%endfor%}				    </p>
			    <h3>{{entry.title}}</h3>
			    <p>{{entry.articleSummary}}</p>
			    <div class="more-link"><span><i class="fas fa-arrow-right"></i></span> Read Article</div>
		    </div>
	    </div>
    </a>	

	{#Insert the Trending Post#}
	{% if loop.index == 2%}
		{% include 'blog/featured' %}

	{%endif%}
{% endminify %}			    

```
That output looks like this...

```
<a href="http://*Masked URL*/blog/test" class="col-12 col-lg-6 blog-item blog-item-big">
  <div class="blogshadow">
    <div class="bi-image bi-eq">
      <picture>
        <source
          data-srcset="http://*Masked URL*/uploads/blog/_992x558_crop_center-center_82_line/bigstock-Professional-Competence-Test-103244267-e1553676793777.jpg.webp 992w, http://*Masked URL*/uploads/blog/_768x432_crop_center-center_60_line/bigstock-Professional-Competence-Test-103244267-e1553676793777.jpg.webp 768w, http://*Masked URL*/uploads/blog/_576x324_crop_center-center_60_line/bigstock-Professional-Competence-Test-103244267-e1553676793777.jpg.webp 576w"
          data-sizes="100vw"
          type="image/webp"
        />
        <img
          class="lazyload"
          src="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%27992%27 height=%27558%27 style=%27background:%23CCC%27 /%3E"
          data-srcset="http://*Masked URL*/uploads/blog/_992x558_crop_center-center_82_line/bigstock-Professional-Competence-Test-103244267-e1553676793777.jpg 992w, http://*Masked URL*/uploads/blog/_768x432_crop_center-center_60_line/bigstock-Professional-Competence-Test-103244267-e1553676793777.jpg 768w, http://*Masked URL*/uploads/blog/_576x324_crop_center-center_60_line/bigstock-Professional-Competence-Test-103244267-e1553676793777.jpg 576w"
          data-sizes="100vw"
        />
      </picture>
      <div class="bi-gradient"></div>
    </div>
    <div class="bi-content eq2">
      <p class="bi-category"></p>
      <h3>Test</h3>
      <p>test</p>
      <div class="more-link">
        <span><i class="fas fa-arrow-right"></i></span> Read Article
      </div>
    </div>
  </div>
</a>

...


```

but no luck. It just doesn't seem to be working at all.

Any insight? Are there any settings in htaccess that would override this?

Thanks

**Comment by kerns** [comment]
@ambidustrious I agree that it's not working – it seems to work in one or two places, but definitely seems sporadic and I've tried and double-checked a lot of things at this stage.

@khalwat It's probably not that important, but it is curious.

**Comment by khalwat** [comment]
Probably you're viewing this in local dev; it's off by default in local dev if you have `devMode` on as per: -> https://github.com/nystudio107/craft-minify/blob/v1/src/config.php#L29

**Comment by kerns** [comment]
Thanks Andrew. Sorry I missed that. But let me make the case this is not the right default. :-) Because...

1) Anyone using this will want to know that it's not introducing any breaking layout changes, and you test those in dev.

2) And if you DON'T want to apply it under dev (and don't know about the option to create an optional config file) you have multiple ways of addressing it – such as just removing the tags, or wrapping them in a conditional based on your path.

I can imagine others have tried this and just assumed it was broken or no longer updated and didn't bother filing an issue. Not a tragedy in and of itself in a world on fire, ...but avoidable.

**Comment by ambidustrious** [comment]
It still doesn't work unfortunately. Even with the config settings or changing to production mode.  It seems to be the same result on all of my sites.... but not sure what would be causing it

**Comment by ambidustrious** [comment]
Scratch that... it now works. I was looking at the wrong site! Thanks!

**Comment by marten-wirelab** [comment]
This default is fine for me, but it should be reflected in the documentation: https://nystudio107.com/docs/minify/#minify-craft-config-settings
> `disableTemplateMinifying` if set to `true` then Minify will not minify anything
> `disableDevModeMinifying` if set to `true` then Minify will not minify anything if `devMode` is enabled

That should really state that `disableDevModeMinifying` is true by default

**Comment by khalwat** [comment]
Would be awesome if you PR'd the docs with your desired change @marten-wirelab 

https://github.com/nystudio107/craft-minify/edit/v1/docs/docs/index.md
