### ISSUE TITLE
idea: excluding entry types via config

### ISSUE THREAD

**Issue by jensfranke** [nystudio107/craft3-minify#2]
I try to exclude the minification for our search, because minfication really slows down the search, but something like this doesn't work:

```
{% if entry.type != 'search' %}
	{% minify %}
{% endif %}
{{ content }}
{% if entry.type != 'search' %}
	{% endminify %}
{% endif %}	
```

**Comment by khalwat** [comment]
Can you put the search results in a separate template or such, without the `{% minify %}` tags?
