### ISSUE TITLE
Upgrade to php8

### ISSUE THREAD

**Issue by Lennso** [nystudio107/craft3-minify#21]
Hey Andrew,

i try to update my craft installation to php 8 with composer and i got this error message:
`Problem 2
    - mrclay/minify 3.0.10 requires php ^5.3.0 || ^7.0 -> your php version (8.0; overridden via config.platform, actual: 8.0.1) does not satisfy that requirement.
    - nystudio107/craft-minify 1.2.10 requires mrclay/minify ^3.0.10 -> satisfiable by mrclay/minify[3.0.10].
    - nystudio107/craft-minify is locked to version 1.2.10 and an update of this package was not requested.`
    - 
I think this issue is related to [https://github.com/mrclay/minify/issues/681](url)

**Comment by khalwat** [comment]
Yep, you can't use PHP 8 with Minify currently due to the reliance on an underlying package that is not PHP 8-ready yet

**Comment by jonathanmelville** [comment]
@Lennso If you're having this issue within your local dev environment, like say vagrant, you can work around it by referencing a different PHP version for the CLI when running your update: `$ php7.4 /usr/local/bin/composer update`

**Comment by khalwat** [comment]
I'm thinking you can also trick Composer with `--ignore-platform-reqs` or by setting the `platform` to something like: https://github.com/nystudio107/craft/blob/craft-webpack/cms/composer.json#L27

**Comment by aurexs** [comment]
It seems that the underlying package has already been updated to support PHP 8 in version [3.0.11 (2021-03-11)](https://github.com/mrclay/minify/compare/3.0.10...3.0.11#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34) 😄

**Comment by khalwat** [comment]
Thx @aurexs -- this should be fully resolved then.
