### ISSUE TITLE
Removing spaces after new lines

### ISSUE THREAD

**Issue by Coysh** [nystudio107/craft3-minify#24]
### Describe the bug
I've got a bunch of components that have classes spread across multiple lines, to make it easier to read:
```
<input
		class="
			{% if bgColor is defined and bgColor == 'gray' %}
				bg-secondary-200 
			{% else %}
				bg-white 
			{% endif %}
			max-w-full 
			w-full 

			{% if label is not defined %}
				h-full
			{% endif %}
			
			py-3 
			px-3 

			text-black 
			placeholder-gray-600 
			
			rounded-md 
			border-3 
			border-transparent 
			border-solid 
			
			focus:outline-none 
			focus:border-primary-200 
			{{ inputClass }}
		"
```

When wrapped in a `{% minify %}` block, the output removes new lines and the spaces after them.
```

<input class="
bg-white
max-w-full
w-fullh-full
py-3
px-3text-black
placeholder-gray-600
rounded-md
border-3
border-transparent
border-solid
focus:outline-none
focus:border-primary-200
"
```

Understand this may be a limitation of the plugin, but any suggestion of a workaround?

**Comment by khalwat** [comment]
I'm unclear what you're stating the bug is here? What's the expected behavior you want to see?

**Comment by Coysh** [comment]
@khalwat  Hey Andrew, as you can see in the outputted class - it's removing some spaces.. i.e. `w-fullh-full` should have a space as in `w-full h-full`.
Minify is taking removing both newlines and spaces on some lines (seems to be if there is a blank line) and keeping the space on others

**Comment by khalwat** [comment]
So if you view the raw source, that space should be replaced with a line feed, which should fine. This is just how it works:

https://github.com/nystudio107/minify/issues/3#issuecomment-167959169

If there is still an issue, you might need to just not minify your component code, or you can file an issue on the Minify repo (which is what the plugin uses): 

https://github.com/mrclay/minify
