### ISSUE TITLE
Twig loop executes much more slowly without any output

### ISSUE THREAD

**Issue by mark-adigital** [nystudio107/craft3-minify#4]
Hi,

I have observed an issue whereby performance suffers greatly when minify tags contain a Twig loop that doesn't have any output. Adding an empty `<span>` tag to the loop eliminates the issue and the loop is performing several conditionals.

Thanks,

Mark

**Comment by khalwat** [comment]
hrm. I'm not sure if there's much I could do about this, it's probably an issue with the core Minify:

https://github.com/mrclay/minify

I could preflight it, but that'd just be paving over the problem.

**Comment by mark-adigital** [comment]
Ok, thanks for looking into it. I've [raised an issue](https://github.com/mrclay/minify/issues/637) in the core library now.
