### ISSUE TITLE
'Ignore' minify block tag

### ISSUE THREAD

**Issue by angelokeirsebilck** [nystudio107/craft3-minify#49]
### Is your feature request related to a problem? Please describe.
Im using the minify tag in my global-vars.twig template that all other templates extend from. In one block i'm using AlpineJS but because my minify tags minify everything somehow this breaks the AlpineJS x-data attribute code.

Removing minify fixes this.

### Describe the solution you would like
Two twig tags: ignore-minify-start and ignore-minify-end to set around the alpine component.

### Describe alternatives you have considered
I could refactor my code to minify only certain blocks and not all html.

**Comment by khalwat** [comment]
Yeah this is deep in the PHP Minify library that Minify uses, and I'm not sure an exclusion tag is something that it'd be reasonably possible for me to implement unfortunately.
