### ISSUE TITLE
disableDevmodeMinifying not working 

### ISSUE THREAD

**Issue by bymayo** [nystudio107/craft3-minify#6]
I've got a minify.php file in my config settings, with this:

```
<?php
   return array(
      'disableDevmodeMinifying' => true
   );
```

But it doesn't seem to disable minifying AND `devMode` is on (I double checked this by using `{{ craft.app.config.general.devMode }}` which returned `1`.

If I change the setting to `disableTemplateMinifying`, then it disables minifying perfectly. But I want to only do this if `devMode` is on

**Comment by khalwat** [comment]
Huh, thanks, I'll have a look.

**Comment by khalwat** [comment]
So I'm not sure how/why this could be happening for you. I went in and changed the default to be:

```php
'disableDevmodeMinifying' => true
```

...because I think that's what most people will want anyway, and it's definitely having an effect.

**Comment by khalwat** [comment]
https://github.com/nystudio107/craft-minify/releases/tag/1.2.9
