### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by LauraMontgomery** [nystudio107/craft3-minify#9]
Hi Andrew,

Just a small one. I came across a typo which had me chasing my tail for ages until I spotted a different case/spelling in the notes on the [latest version release](https://github.com/nystudio107/craft-minify/releases/tag/1.2.9).

The default is now to NOT minify templates, which I agree is what most people will want. However, in my particular case I wanted minified templates in devMode. The typo is under [Minify craft.config settings](https://github.com/nystudio107/craft-minify#minify-craftconfig-settings).

When I set my minify.php config to:

`'disableDevmodeMinifying' => true`

it doesn't work, but

`'disableDevModeMinifying' => true`

does work - note the spelling DevMode not Devmode.

This may be the same issue that Jason Mayo was having [here](https://github.com/nystudio107/craft-minify/issues/6).

The same spelling/case is used for Craft 2 but may not be an issue there.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-minify/commit/e89c1f3fa4e26face422614fcb6edf57fdce9dfc
